language:
  - php
  - node_js
php:
  - '7.0'
node_js:
  - 'node'
install:
  - composer install --quiet
script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs app --standard=psr2
before_deploy:
  - zip -rq latest * .*
  - test -d dpl_cd_upload || mkdir dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
deploy:
  - provider: s3
    access_key_id: AKIAIZJULZXBORRZ6CBA
    secret_access_key:
        secure: XorYV18PTu2vtpdlnBfDjF7KJFWfkkI2C79LiO8cIiyG+7MYh/DoKfDc48ZZYQs3obkTUdKIaQvetUsx0PRbUrRht7PayT6de0iP8l4LggFNYpH8rXPNg+VPSWm4Yf+PXimvIBAGmS65IibIuTJHk2dwkwuSty7NausOqR0JD3xt+SEkAfKsDAjxQ/ikawZXLGsHlbq/DN9zhGy9pvkOFXW0KstJ+1zTXxGEH0NlBKIQsJcEvQTqJrkORNMHYpt/mCDdu7rbTicK9PzXRRgw+oGe+v5nA+VN2/EE74EI4z1hM4dPhPk2pPfZU7TrMl/TxVVyoatyWyZL0EhLKWeS9Knkwyv8wDCExZLDpASf9+0zj0+XYkojGvNsflKZYlcprt15eHVxi6Pl5YcvYGYgL1hM0cOxuejnbGIv3jWRwaxlLhdI2Th/894YA5O8K3yOcqTKFBELCY7fv+wBkfwGzWicnEN87nwk5rKBzEZEI9XsaNfIAMb9ahFhmyvGX7taL1MPpH4HDUHDXGssai9ZRPfIpYTxJFo1DnRNfY/tvRg3UXhtfnA1j3EXyoiafDcRvk+ghJDEXddnTSnb4Di08c1vDZkyApMc37CDJrUKE3dPuGDySV2nDEbDDlZzYP37e9EmR+AibBs1JqzWyqe4mkNbrhPLJFTSJZzz33c+OPc=
    local_dir: dpl_cd_upload
    skip_cleanup: true
    on:
      branch: staging
    bucket: travis-codedeploy
  - provider: codedeploy
    access_key_id: AKIAIZJULZXBORRZ6CBA
    secret_access_key:
        secure: XorYV18PTu2vtpdlnBfDjF7KJFWfkkI2C79LiO8cIiyG+7MYh/DoKfDc48ZZYQs3obkTUdKIaQvetUsx0PRbUrRht7PayT6de0iP8l4LggFNYpH8rXPNg+VPSWm4Yf+PXimvIBAGmS65IibIuTJHk2dwkwuSty7NausOqR0JD3xt+SEkAfKsDAjxQ/ikawZXLGsHlbq/DN9zhGy9pvkOFXW0KstJ+1zTXxGEH0NlBKIQsJcEvQTqJrkORNMHYpt/mCDdu7rbTicK9PzXRRgw+oGe+v5nA+VN2/EE74EI4z1hM4dPhPk2pPfZU7TrMl/TxVVyoatyWyZL0EhLKWeS9Knkwyv8wDCExZLDpASf9+0zj0+XYkojGvNsflKZYlcprt15eHVxi6Pl5YcvYGYgL1hM0cOxuejnbGIv3jWRwaxlLhdI2Th/894YA5O8K3yOcqTKFBELCY7fv+wBkfwGzWicnEN87nwk5rKBzEZEI9XsaNfIAMb9ahFhmyvGX7taL1MPpH4HDUHDXGssai9ZRPfIpYTxJFo1DnRNfY/tvRg3UXhtfnA1j3EXyoiafDcRvk+ghJDEXddnTSnb4Di08c1vDZkyApMc37CDJrUKE3dPuGDySV2nDEbDDlZzYP37e9EmR+AibBs1JqzWyqe4mkNbrhPLJFTSJZzz33c+OPc=
    bucket: travis-codedeploy
    key: latest.zip
    application: assistant
    deployment_group: assistant-group
    region: ap-northeast-1
    on:
      branch: staging
    wait-until-deployed: true
